name: "Lint Python Code"
on:
  push: #only execute on push to master
    branches:
      - master
    
  pull_request:
    branches:
      - master
    

jobs:
  lint: # name of the job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install ruff
          
      - name: Lint the project
        run: ruff check --output-format=github
